FROM rabbitmq:4.0-management

RUN echo "[rabbitmq_management,rabbitmq_prometheus,rabbitmq_stream,rabbitmq_stream_management]." > /etc/rabbitmq/enabled_plugins
ENV RABITMQ_ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins
